### ISSUE TITLE
Rocket launching and re-entry is incredibly difficult

### ISSUE THREAD

**Issue by hayhay7789** [VenVen/Stock-Revamp#101]
It is very difficult if not impossible to start a new Career game with this mod installed.

When building my first rocket I put only the Mk1 command module, a Flea booster and a parachute on. No matter what I try I smash into the ground every time. My speed is always >400m/s on the return, and parachute is not safe to deploy at any time (red icon) so I just end up exploding into the ground. Essentially this mod is changing too much with the physics to make it possible to get past the first launch in a career mode game.

**Comment by hayhay7789** [comment]
Disabled this to get the first rocket done - now trying to fly up to ~60,000m and come back down, still having the same issues. The speed I reenter at is ridiculously high (~1000m/s) and I am totally unable to slow down in time.

**Comment by Stratickus** [comment]
The performance of the stock parachutes is changed with VSR.  The file is a config titled Utility, located here if you want to remove/edit it:

VenStockRevamp >  Sqaud > Parts
