### ISSUE TITLE
1.9.6 Version Information Wrong

### ISSUE THREAD

**Issue by tstivers1990** [VenVen/Stock-Revamp#105]
The version information for 1.9.6 is wrong. AVC shows it as 1.9.5 compatible with 1.1.3 even though I've triple checked I'm downloading the right version.

**Comment by Kerbas-ad-astra** [comment]
Should be fixed by #100.

**Comment by khr15714n** [comment]
Started KSP:
_KSP Add-on Version Checker
VenStockRevamp 1.9.5 (current) 1.9.7 (avail)_

Installed through CKAN, listed as 1.9.6
1st came here, wondered were 1.9.7 is and download 1.9.6
Compared installed files with downloaded ... 100% identical
downloaded (github) VenStockRevamp.version reads 
  "VERSION": {
    "MAJOR": 1,
    "MINOR": 9,
	"PATCH": 5
  },
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 1,
    "PATCH": 3
  }
while
http://forum.kerbalspaceprogram.com/index.php?/topic/83696-122-stock-part-revamp-update-196-released-source-files/
reads 1.2.2 and version 1.9.6

---------------------

https://github.com/VenVen/Stock-Revamp/blob/master/GameData/VenStockRevamp/VenStockRevamp.version
reads
  "VERSION": {
    "MAJOR": 1,
    "MINOR": 9,
	"PATCH": 7
  },
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 2,
    "PATCH": 2
  }

Seems you've never updated the zip file for version 1.9.7
