### ISSUE TITLE
Issue with part mass balance

### ISSUE THREAD

**Issue by rossmane** [VenVen/Stock-Revamp#108]
I have not looked at all parts but when attempting to balance the mass of the Mk 1-2 cmd pod I noticed that it was offset towards the door of the pod. This makes radial thrusters imbalanced and makes propulsive landing annoying.

**Comment by blowfishpro** [comment]
The point might have been to give it some lift on re-entry.  I guess you can't have it both ways...

**Comment by rossmane** [comment]
Why only give it to that part? Why not the other capsules? Anyway, I think my more important question is is there a way to fix it for my game files.

**Comment by NathanKell** [comment]
Because the Mk1 pod is modeled after Mercury and that had ballistic reentry, whereas the Mk1-2 pod is kinda Apollo, which did lifting?

To change: remove this line:
https://github.com/VenVen/Stock-Revamp/blob/master/GameData/VenStockRevamp/Squad/Parts/Command.cfg#L9
