### ISSUE TITLE
Was the LongDeployableAntenna intentionally deprecated?

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [VenVen/Stock-Revamp#121]
The config file (commsDish32.cfg) was removed but not added to the consolidated config files, but the model is still present (VenStockRevamp/Squad/Parts/ScienceParts/LongAntenna).  Was the part not supposed to be removed?

**Comment by VenVen** [comment]
No, it looks like it was missed during the update.

**Comment by VenVen** [comment]
Re-added as of 95f2ca5
