### ISSUE TITLE
Automatic release builds

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#19]
@VenVen would you be interested in a script that automatically built your release file whenever you click "draft a release" on github? Then you could grab that file and point curse at it, too.
(This will also make CKAN integration much, much easier, which was the original reason I became involved, aside from awesomeness of parts :D )

**Comment by NathanKell** [comment]
@VenVen just checking in--but don't feel the need to reply if you're still on break ( :) ) or exams ( :( ) but I was wondering if you'd had a chance to check this out.

**Comment by VenVen** [comment]
Ok I'm back, sorry for not getting back sooner. Unfortunately I don't really know how those batch files work, and when I tried using them, they didn't rename anything.

I've updated the pruners (added a De-pruner)  using the original method for the time being.

**Comment by BasharMilesTeg** [comment]
Hi @VenVen, I've corrected my assumption about the 'ren' command and updated the two .bat files. I don't have access to a linux machine to test the .sh files but I did notice that your 1.7 update replaced them with windows commands. If you would like my script to generate these five files for your 1.7 release it would probably be wise to test them more widely. Do you do an early release to testers?

We're still looking at how to best handle the automatic packaging side of things.

Finally whilst working on this I noticed that the primary Part Revamp-MM.cfg file is quite large at 2590 lines, why not have it portioned out to go with each folder to make it easier to handle?

**Comment by NathanKell** [comment]
(which chopping up we can do if you like)

Regarding the automation, @BasharMilesTeg does have a MM patch and pruner builder that works off your files, so with your permission we can get the automation set up. You will still need to make the part of the MM patch that doesn't just deal with the model (i.e. adding extra MODULEs or patching existing ones if things change) but it should automate a fair amount of the cfg workload, and *all* the pruner workload. :)

**Comment by Felger** [comment]
@BasharMilesTeg, I've released [AutoPruner V1.0](https://github.com/Felger/AutoPruner/releases/tag/v1.0), which fixed some bugs and added some functionality, you're more than welcome to use that as a means for your pruning.

**Comment by BasharMilesTeg** [comment]
I've updated the script to generate [VSR.prnl](https://gist.github.com/BasharMilesTeg/49dcc924d8ca09f0c778) which can be used with @Felger's AutoPruner to prune the stock files in the same manner as the shell scripts above. Whilst I've tested the .bat files to make sure that they actually rename models and textures I don't know if any of the six files miss some, or worse, renames files it shouldn't.

**Comment by BasharMilesTeg** [comment]
Hi @VenVen, how would you like to proceed from here? The script is done, it even produces caches that it can use in an environment where the stock files aren't available. It generates the Part Revamp-PathPatches.cfg, prune.bat, unprune.bat, prune.sh, unprune.sh and VSR.prnl automatically for you so you don't need to edit them by hand.

**Comment by VenVen** [comment]
@BasharMilesTeg Well, forward the script to me (and include something telling me how to use it), and I'll use it in the next update.

Thanks for taking the time to do all of that and putting up with a clueless Ven XD

**Comment by BasharMilesTeg** [comment]
You can run the script on your computer with [node.js](http://nodejs.org/download/) (run "node.exe main.js" in a command prompt) but to setup up automatic builds you'll need to use [travis.ci](https://travis-ci.org) which you can access in GitHub at Settings->Webhooks and Services->Add Service dropdown->Travis CI. Unfortunately I don't know anything further about setting it up but once it is I'll look at getting the script running automatically.

**Comment by NathanKell** [comment]
And @VenVen if you tell me a time you can be on #kspmodders on espernet I can walk you through it.

**Comment by NathanKell** [comment]
(It's something only you, as repo *owner*, can set up)

**Comment by VenVen** [comment]
@BasharMilesTeg I've run your script but have run into some problems. It seems that it refers to to old module manager cfg that is no longer present after I split it into smaller parts. When I recombine them, I get this error in CMD:

"pathCache.json written.

F:\Games\Kerbal Space Program\main.js:95
if (!path.extname(stockCfgs[arr[1]].mesh)) { // model = style
TypeError: Cannot read property 'mesh' of undefined
at F:\Games\Kerbal Space Program\main.js:95:44
at Array.forEach (native)
at F:\Games\Kerbal Space Program\main.js:91:67
at fs.js :272:14
at Object.oncompleate (fs.js:108:15)"

The files are then written as blanks aside from the .json files.

Aside from that, It seems to work in earlier (pre-MM file breakup) files.

@NathanKell If you still have time to help, I'll be on #kspmodders for most of the day (and if this is missed, most other days are an option as well).

Thanks for all of the help! Ven~

**Comment by BasharMilesTeg** [comment]
I've updated the script #30
