### ISSUE TITLE
Starting capital letters causes some engines to not load?

### ISSUE THREAD

**Issue by aw1621107** [VenVen/Stock-Revamp#25]
Rather odd issue, and I'm not sure if this is possibly OS-specific (case-sensitive filesystems, anyone?), so creating an issue rather than a pull request.

Some of the VSR engines didn't load on my copy of KSP (OS X 10.10.2), and seems that changing their names to start with a lowercase letter instead of an uppercase one allows them to load just fine.

The engines that I know of so far with this behavior are:

- LV-1B (MicroEngineB --> microEngineB)
- LV-909B (VenLV909B --> venLV909B)

I'm not really sure why this is, or if it even is an issue for most users, but thought you'd like to know.

**Comment by aw94** [comment]
Found another engine, but this time it's a lowercase starting letter that's causing the issue:

engineSkipperButtless --> EngineSkipperButtless
