### ISSUE TITLE
Consistent version numbers

### ISSUE THREAD

**Issue by TeddyDD** [VenVen/Stock-Revamp#27]
Hello @VenVen 
Could you keep numbering your releases with "v" at the beginning like "v1.7.2" instead of "1.7.2"
There is nothing wrong with new version numbers but CKAN compare version numbers alphabetically so "v1.7.1" > "1.7.2". However if you prefer to stay with new system I can fix this in CKAN side but I think  It would be less effort to rename your release/tag (not sure, I've never created any release on github) Whatever you decide it would be really good if you could keep your versions numbers consistent in next releases :smiley: 

Thanks for your great work! :rocket:

reference CKAN issue KSP-CKAN/NetKAN#924

**Comment by NathanKell** [comment]
I made a fresh v1.7.2 release to get around this issue.

**Comment by pjf** [comment]
Yay! Reindexed on CKAN. We can close this!

**Comment by TeddyDD** [comment]
Thank you @NathanKell :)
