### ISSUE TITLE
Cupola and Mk2 lander can window reflections not working with TextureReplacer

### ISSUE THREAD

**Issue by slikts** [VenVen/Stock-Revamp#37]
The cupola and Mk2 lander can window reflections aren't working; video example: http://a.pomf.se/gtccmr.mp4

This is a clean KSP 1.0.2 install; no other mods except Ven's 1.8.1, Module Manager 2.6.5 and TextureReplacer 2.4.4 installed from CKAN.

**Comment by VenVen** [comment]
The Mesh objects didn't have the correct names in the configs, I've updated the repo and they work great now!

Thanks for reporting this (sorry for taking so long to reply)!
