### ISSUE TITLE
Mk16 parachute not working

### ISSUE THREAD

**Issue by bgse** [VenVen/Stock-Revamp#40]
The Mk16 parachute isn't working, it doesn't get the parachute icon thingy in the staging sequence, and you can't manually deploy it either.

RealChute is installed, as well as a couple of other mods such as KER and RPM. The problem starts when installing StockRevamp, and is resolved by removing it, so it probably is somewhere in here.

**Comment by LPGhatguy** [comment]
I can confirm that this is happening with just RealChute and StockRevamp, @VenVen. It appears that the mk16 chute is being scaled down and is clipping into the Mk1 pod.
