### ISSUE TITLE
Request: Inline RCS block transform change

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#41]
@VenVen  if you have a chance, could you change the RCS thrust transforms on the inline RCS block to be two per side and pointing 90 degrees opposed to the way they are now?

As they are now:
```
           ^
           |
         __o__
        /      \
   <--o|        |o-->
        \__o__ /
           |
           v
```
My request:
```
      <_____>
    ^  __o__   ^
    | /      \ |
    o|        |o
    | \__o__ / |
    v <----->  v
```
This would allow one to roll with RCS; it wasn't aligned like that on Mercury only because the pod itself had roll thrusters, but since the Mk1 pod obviously doesn't, I'd suggest taking the Gemini approach (the second illustration above).

To not double the thrust, since the number of transforms are doubled you should halve thrusterPower., to 0.25. Note that your HeavyRCS in fact has 4x the thrust of a single block, because it has 8 nozzles rather than 4, each producing 2kN, whereas the original has 4 nozzles at 1kN; this is the opposite of engines, where the stated power is the total power of the engine and it's apportioned amongst the transforms.

**Comment by NathanKell** [comment]
Edited for correctness / more info.

**Comment by VenVen** [comment]
I've changed the RCS transforms and It should now work as you've described.

**Comment by NathanKell** [comment]
Awesome! Thanks so much!
