### ISSUE TITLE
Missing INTERNAL defines

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#43]
@VenVen  you added the assets and patched the INTERNAL {} nodes on parts, but didn't actually add the cfgs that define the internals. So KSP dies whenever a changed-IVA part is loaded, because it can't find the internal of that name.
Is it supposed to be more or less the same as the old internal.cfg for each?

**Comment by VenVen** [comment]
Hmm... That's really strange, my github client seems to ignore the .cfg files entirely. Actually all .cfg files are ignored. :/

**Comment by NathanKell** [comment]
@VenVen  In your IVA commit, you set Git to ignore *.cfg, as well as
GameData/VenStockRevamp/Part Bin/ExtraEngines.cfg
GameData/VenStockRevamp/Squad/Parts/FuelTanks.cfg
in particular.

If you right-click on a file and choose 'ignore' then git will ignore it. If you right-click and choose 'ignore all .whatever" it will ignore all. If you just don't want to *include it in a commit,* then just *uncheck it* -- ignore doesn't mean "for this commit" it means "permanently". :)

I have updated the repo to no longer ignore any of those files. Can you sync from the repo, then commit everything changed?

**Comment by VenVen** [comment]
Ok It works now.

Thanks for fixing it!

**Comment by NathanKell** [comment]
Hurrah!
Sure! :)
