### ISSUE TITLE
MK1 Inline Cockpit model - flag textureQuadName change breaks game

### ISSUE THREAD

**Issue by somnambulistic** [VenVen/Stock-Revamp#44]
The flag texture quad in the new Mk1 Inline cockpit model does not match the textureQuadName from the stock CFG and model. This displeases KSP greatly. 

Here's an excerpted log from when the game switches out of the VAB to launch. This is from a test install with only stock KSP, ModuleManager and Strock Revamp. The game throws constant NaN errors and the entire camera view "bounces".

    [WRN 11:57:49.401] [FlagDecal Warning!]: Flag quad object is given as FLAG, but no object found in model with that name
    [EXC 11:57:49.402] IndexOutOfRangeException: Array index is out of range.
    	ModuleAnimateGeneric.OnStart (StartState state)
    	Part.ModulesOnStart ()
    	Part+.MoveNext ()
    [ERR 11:57:49.425] Scene::raycastClosestShape: The maximum distance must be greater than zero!
    
    [LOG 11:57:49.425] Look rotation viewing vector is zero
    [LOG 11:57:49.546] [ScenarioDestructibles]: Loading... 0 objects registered
    [LOG 11:57:49.547] Loading Depletion Nodes
    [LOG 11:57:49.548] DepNodeCount:  0
    [LOG 11:57:49.548] Loading Biome Nodes
    [LOG 11:57:49.548] BiomeNodeCount:  0
    [LOG 11:57:49.549] Loading Planet Nodes
    [LOG 11:57:49.549] PlanetNodeCount:  0
    [ERR 11:57:51.802] Scene::raycastClosestShape: The maximum distance must be greater than zero!
    
    [LOG 11:57:51.803] Look rotation viewing vector is zero
    [LOG 11:57:51.803] [AsteroidSpawner]: No new objects this time. (Odds are 1:2)
    [LOG 11:57:51.841] [Progress Node Reached]: RecordsSpeed
    [LOG 11:57:51.906] [PlanetariumCamera]: Focus: Untitled Space Craft
    [WRN 11:57:51.961] [CurrencyWidgetsApp]: No live widgets to Despawn!
    [LOG 11:57:52.146] Flight State Captured
    [LOG 11:57:52.146] Saving Achievements Tree...
    [LOG 11:57:52.148] Active Vessel is moving (sqrVel = 30469.3657932693). Cannot save.
    [LOG 11:57:53.175] [Untitled Space Craft]: ground contact! - error: 0.038m
    [LOG 11:57:53.176] Unpacking Untitled Space Craft
    [LOG 11:57:53.186] nearestTT is NaN! t1: 0, t2: 0, FEVp: NaN, SEVp: NaN
    [LOG 11:57:53.188] problem! 
    [NaN, NaN, NaN]  -  [NaN, NaN, NaN]  -  NaN  -  [NaN, NaN, NaN] - 0
    [LOG 11:57:53.189] problem! 
    [NaN, NaN, NaN]  -  [NaN, NaN, NaN]  -  NaN  -  [NaN, NaN, NaN] - 0
    [LOG 11:57:53.189] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.189] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.190] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.190] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.192] nearestTT is NaN! t1: 0, t2: 0, FEVp: NaN, SEVp: NaN
    [LOG 11:57:53.192] problem! 
    [NaN, NaN, NaN]  -  [NaN, NaN, NaN]  -  NaN  -  [NaN, NaN, NaN] - 0
    [LOG 11:57:53.193] problem! 
    [NaN, NaN, NaN]  -  [NaN, NaN, NaN]  -  NaN  -  [NaN, NaN, NaN] - 0
    [LOG 11:57:53.194] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.194] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.194] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.195] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.195] problem! 
    [NaN, NaN, NaN]  -  [NaN, NaN, NaN]  -  NaN  -  [NaN, NaN, NaN] - 0
    [LOG 11:57:53.196] problem! 
    [NaN, NaN, NaN]  -  [NaN, NaN, NaN]  -  NaN  -  [NaN, NaN, NaN] - 1.35999999999997
    [LOG 11:57:53.197] [Progress Node Reached]: RecordsDistance
    [LOG 11:57:53.205] nearestTT is NaN! t1: 0, t2: 0, FEVp: NaN, SEVp: NaN
    [LOG 11:57:53.205] problem! 
    [NaN, NaN, NaN]  -  [NaN, NaN, NaN]  -  NaN  -  [NaN, NaN, NaN] - 0
    [LOG 11:57:53.206] problem! 
    [NaN, NaN, NaN]  -  [NaN, NaN, NaN]  -  NaN  -  [NaN, NaN, NaN] - 0
    [LOG 11:57:53.206] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.207] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.207] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.208] getObtAtUT result is NaN! UT: NaN
    [LOG 11:57:53.210] nearestTT is NaN! t1: 0, t2: 0, FEVp: NaN, SEVp: NaN
    [LOG 11:57:53.210] problem!

**Comment by VenVen** [comment]
Thanks for reporting this! It seems that Squad changed the flag name in 1.0.4, which caused the problem.

Though I think displeases is putting it too lightly, KSP starts flipping tables when it's flags aren't in proper order. XD
