### ISSUE TITLE
Suggestion/Request: Add an RD-107/8 like engine

### ISSUE THREAD

**Issue by TheKosmonaut** [VenVen/Stock-Revamp#46]
Hello,

You think making an engine like this (https://en.wikipedia.org/wiki/RD-107) would be doable? It'd be really great for an RO/RP-0 user. Need more communist hardware:D

**Comment by NathanKell** [comment]
@Ven it would fit quite well in stock, too--as a 2.5m engine, say, with somewhat better efficiency than the Mainsail but lower than the Skipper. Or, conversely, as an early, cheap 2.5m engine, for before one gets the others (as the LV-T15 is for the 1.25s).

**Comment by VenVen** [comment]
This is what I came up with, along with what I believe to be two Aerobee engines (150 and 350?):
http://imgur.com/a/19rjy

The 107 lacks a bottom fairing, but that can be added With a few config edits (I've included the base fairing model as a separate .mu)

**Comment by NathanKell** [comment]
Ah, neat!

Question: Is there stuff under the boattail for the RD-107? As in RO use at least, people would probably be creating their own boattails (it's why RO uses your old Mainsail model, not your new one)

**Comment by NathanKell** [comment]
(I presume there is not, for the Aerobee engines--though that would be great too.)

**Comment by VenVen** [comment]
Unfortunately neither have internals. :/
