### ISSUE TITLE
Issue with "LV-N" Nerv Engine

### ISSUE THREAD

**Issue by jasonlewis** [VenVen/Stock-Revamp#49]
Having a weird issue with the Nerv engine which I'm assuming has to do with this mod.

This is the engine without the mod enabled.

![screenshot_2015-08-02--21-53-55](https://cloud.githubusercontent.com/assets/829059/9026003/73ecb32e-3961-11e5-9fa2-ba6e41493279.png)

And this is what I'm seeing with the mod enabled. I couldn't even get the fourth engine on.

![screenshot_2015-08-02--21-56-28](https://cloud.githubusercontent.com/assets/829059/9026004/73ed4b90-3961-11e5-9b72-d51d829050c4.png)

Let me know if there's any further debugging I can do for you.

**Comment by VenVen** [comment]
That's an issue with the auto-fairing included with the engine, and it is difficult to get the right mix of ease of use and creating clipping or floating issues (It uses a second attach node to activate the fairing). I've never seen the symmetry problem before though.

Thanks for taking the time to report this!

**Comment by jasonlewis** [comment]
No worries mate. I'm guessing the symmetry issue is something else entirely? Problem with vanilla KSP?

**Comment by VenVen** [comment]
The odd symmetry may be a stock issue, but I can't say for sure.

**Comment by Chrisplus** [comment]
I met with this problem too. 

When attaching parts under LV-N, 1.25m fairings will be added automatically. But the size of auto fairing above LV-N is 2.5m.
