### ISSUE TITLE
LV-1 Ant Engine bug - NullRefs and in-flight issues.

### ISSUE THREAD

**Issue by Poodmund** [VenVen/Stock-Revamp#53]
I'm experiencing an issue with the "Ant" LV-1 where it is throwing up:

Code: [Exception]: NullReferenceException: Object reference not set to an instance of an object
NullRefs

... in the VAB and then on launch the engine staging icon is not listed in the staging order. When launching a vehicle with an "Ant" LV-1 included the craft gets to around 300m/s and the camera zooms out and then this happens again periodically at higher instances of speed. The craft will eventually (around orbital velocity) instantaneously explode and accelerate up to crazy high velocity and sometimes the game will crash at this point. I've also encountered heating issues with craft that include this engine where parts around it will rapidly overheat.

The part in question is the "microEngine" and this was testing on a clean install with the latest build of VSR using commit 694e845ba2 26th Aug and occurs running at x86 and x64.

To replicate this on a clean install I started a new Sandbox, then built the following craft, Mk1 Command Pod > FL-T400 Tank > LV-1 Ant Engine > TR-18A Stack Decoupler > FL-T800 Tank > LV-T45 Engine, with all the fire-able stages in separate stages.

Also note that I first noticed this issue/bug when using my heavily modded install so it seems the problem persists at the clean install level. I noticed in the config file that there is a fairing jettison module for this engine relating to a tankbutt but I am not sure if a tankbutt is included on this engine, could that be the module culprit? Anyway, would someone please verify this issue too?

**Comment by blowfishpro** [comment]
This is the result of a ModuleJettison with jettisonName = TankButt (but no transform named TankButt exists).
