### ISSUE TITLE
Prune without breaking stock model mods

### ISSUE THREAD

**Issue by Prezombie** [VenVen/Stock-Revamp#57]
If instead of moving stock bits to .bak, how about moving them to .bak, moving the revamped files into the stock locations, and pointing the configs to them instead? It would save ram, as well as automatically revamping a piece that borrows a stock model or texture.

**Comment by NathanKell** [comment]
Except that that will not save ram over the pruner as it exists (files in
folder a take up just as much space as files in folder b...) and anything
referencing a patched model via a MODEL node will already be patched by the
pathpatches included in this.

Sent by my thumbs, slowly.
