### ISSUE TITLE
Releasing a build

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#59]
@VenVen would you mind if I released a build via github? There's been a lot of fixes since the last one.

**Comment by VenVen** [comment]
After I upload a bunch of fixes, I should have that up by tomorrow. Currently I need to go through all of the engine fairing colliders, changing them to proper convex colliders.

**Comment by NathanKell** [comment]
Ah, gotcha. Right, I forgot that issue (AGAIN).

**Comment by blowfishpro** [comment]
@VenVen would it be too much to ask to take a look at some of the open pull requests for this release?  They've been sitting around for quite a while.

**Comment by VenVen** [comment]
@blowfishpro I've added your :FIRST changes, some of the other pull requests, however have been made manually myself.

@NathanKell oh speaking of the fairings, I read somewhere that they now have a specific layer for them (layer 19?) does the layer need to be named anything or can I leave its layer description (tag whatever its called) blank?

**Comment by NathanKell** [comment]
I think setting them to Layer 19 is sufficient.

**Comment by NathanKell** [comment]
@VenVen  Did that work out? What else is remaining? Anything I can help with?

**Comment by VenVen** [comment]
I tried changing the fairings to L19, but when they were ingame, the fairings failed to appear until the engine was re-attached.

Other than that, it's just the pruners and the path patches files. Updating those files would be a snap with 'main.js', but due to my superb foresight, I changed the folder structure, so now it doesn't work. :/

**Comment by NathanKell** [comment]
I'd also like to change the path patches so they're not FINAL, so they can be overridden if needed.
I'm not sure it's really worth updating the pruner--maybe release for now without it, and see how many people howl? And then add back if needed? ^_^

**Comment by NathanKell** [comment]
As for the fairings...oh, right. I don't think you need to layer them yourself, the layer is applied by the code when they are decoupled. While they're still part of the whole fairing part, they *should* still be on the part layer. So...don't think you have to do anything necessarily? Apologies for confusion.

**Comment by NathanKell** [comment]
Yep, no change was made to the assets when that change was made on our end, so I think you don't have to change anything either.

**Comment by VenVen** [comment]
Ok, thanks for responding to that. I've gone and uploaded the modified patches and some other things, So it *should* be ready.

**Comment by NathanKell** [comment]
Awesome!
Also I did a quick tweak to the path patches--I wasn't clear on what I meant, sorry. :)

**Comment by NathanKell** [comment]
@VenVen um, you removed the jet models but, as far as I can tell, left the textures in? That means they can't be used by other mods (like AJE) but they still take up just as much RAM as in 1.8 (since the textures are still included). I'd suggest either including all the relevant files or none of them. : ]

**Comment by VenVen** [comment]
Oops, the textures inside /Propulsion were missed when I removed the old jet engine models. I've moved the old jets into a new folder inside the Part Bin/NewParts folder.
