### ISSUE TITLE
Docking port with parachute does not have parachute staging. 

### ISSUE THREAD

**Issue by kiwivogel** [VenVen/Stock-Revamp#61]
The docking port/parachute combination fails to show up in the staging and  causes collision issues when combined with the 2.5 capsule pod cover (it pops off with the cover when loading the vessel for launch). (I also cannot seem to select it in the action group assignment window.)

**Comment by VenVen** [comment]
I've Updated the parachutes config and the escape cover's model to fix these issues. thanks for reporting this!
