### ISSUE TITLE
NRE's with XXL Chute Docking port

### ISSUE THREAD

**Issue by Sharpspoonful** [VenVen/Stock-Revamp#62]
Adding to the other issues with it, I was getting spammed NRE's with the docking port in both the editor and in the flight scene.

**Comment by VenVen** [comment]
It turned out that two animation modules were looking for the wrong animations, which caused the NRE's and a host of other issues.

Thanks for taking the time to repot this!

**Comment by Sharpspoonful** [comment]
Hey, just got a chance to download 1.9.0. Looks like the NRES have been fixed. Tested both the capsule cove and para-dock and they work flawlessly at most altitudes.
