### ISSUE TITLE
Small ISRU missing model

### ISSUE THREAD

**Issue by PhineasFreak** [VenVen/Stock-Revamp#65]
The "1.25m ISRU Converter" is missing it's model inside the Squad/Parts/ISRU folder (SmallISRU.mu). I am not sure if this is a planned omission or an accidentally missing file.

**Comment by VenVen** [comment]
Somehow it got taken out of the folder, I've moved it to the part bin folder for now.

**Comment by PhineasFreak** [comment]
Since you have taken care of the issue, i am closing this now.
