### ISSUE TITLE
Overlapping textures on the MK 1-2 CM

### ISSUE THREAD

**Issue by lynwoodm** [VenVen/Stock-Revamp#66]
I've used this mod in the past, but since the update, I've gotten this strange quirk with the texturing of this command module. 
![screenshot from 2015-12-11 10 31 20](https://cloud.githubusercontent.com/assets/15900022/11773044/5c51c232-a1f2-11e5-8471-4f78a4ff811a.png)
![screenshot from 2015-12-11 10 31 28](https://cloud.githubusercontent.com/assets/15900022/11773045/5c53b90c-a1f2-11e5-8b06-8256036bff04.png)

I don't know what I've done wrong to get the textures to appear to overlap on the old model, but it's there. Any clues onto how I can fix this?

**Comment by VenVen** [comment]
Something is re-adding the old command pod, what mods do you have installed?

**Comment by lynwoodm** [comment]
Squad is the only mk 1-2 texture I have. I don't have any other mods, other than yours that has anything to do with texture revamping on this pod. I took your mod out to kind of narrow it down to this pod alone and it seems as the original squad file loads two external texture files. Not sure if they are responsible for the results posted. 
 
[LOG 01:18:38.783] Load(Texture): Squad/Parts/Command/Mk1-2Pod/mk 1-2 external shell Variant-Hatch NRM
[LOG 01:18:38.816] Load(Texture): Squad/Parts/Command/Mk1-2Pod/mk 1-2 external shell Variant-Hatch

As far as mods go, I have a lot of them. AVC tells me I have 42 (with yours included)

Oh sure, I have the aset interior revamp, but I feel that has nothing to do with the external part. If you are wondering what mods I have that revamp squad parts, I only have yours that does anything to squad parts. Always used your revamp mod. 


![screenshot from 2015-12-14 03 01 46](https://cloud.githubusercontent.com/assets/15900022/11775762/9505da88-a20f-11e5-9f49-07205eb434ee.png)
![screenshot from 2015-12-14 03 02 01](https://cloud.githubusercontent.com/assets/15900022/11775763/95065f58-a20f-11e5-9317-3ddcf35c01e4.png)

**Comment by NathanKell** [comment]
No, point is, something is adding a MODEL to the part's cfg, via a ModuleManager patch. You need to find all patches that reference PART[Mark1-2Pod]

**Comment by VenVen** [comment]
I'd place my bet on SDHI Service module System, that mod re-adds the stock 1-2 command model along with its umbilical socket.

**Comment by lynwoodm** [comment]
You are bingo on that mod, Ven. And thanks, Nathan, that string of text help me out on this. So, what's the fix? Either delete the mod or have the patch not point back to the original texture losing the umbilical texture?

**Comment by VenVen** [comment]
For now, I'd either delete the problem model node or comment it out with //.

**Comment by lynwoodm** [comment]
I just removed the patch file and it's looking like xmas with that new pod design. Thank you both for your help. Your work is very much appreciated and keep it up. Over and Out!
