### ISSUE TITLE
Launch clamp tower transparency (NK may be an idiot)

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#68]
**EDIT: I may be an idiot.
I forgot I was not running in DX9 mode for this, so it may work fine in DX9 mode. Apologies!**

Hitting an issue with these. They're blanking out some things but not others.
Example:
[![](http://i.imgur.com/d7Qpme3l.jpg)](http://i.imgur.com/d7Qpme3.jpg)
(Proc fairings shroud, proc parts tank, your AV-T1, SXT RD-180)

**Comment by NathanKell** [comment]
**EDIT: I may be an idiot.
I forgot I was not running in DX9 mode for this, so it may work fine in DX9 mode. Apologies!**

**Comment by Kradgger** [comment]
Even then, shouldn't it work fine on DX11?
