### ISSUE TITLE
Small ISRU wrong model path

### ISSUE THREAD

**Issue by PhineasFreak** [VenVen/Stock-Revamp#73]
The part .cfg references the correct model name ("SmallISRU.mu") but with the wrong path to it ("VenStockRevamp/Squad/Parts/ISRU").

I assume that this is an extra part, judging from it's placement inside the "NewParts" folder, so the correct path should be "VenStockRevamp/Part Bin/NewParts/SmallISRU/SmallISRU.mu".

**Comment by FiiZzioN** [comment]
I may be wrong, but that might be an older part. It seems to copy the new, smaller stock 1.25 ISRU which implies it was made when the 2.5 ISRU was the only one available. 

At the time of this comment, I'm still investigating, but I feel pretty strongly that this is the reason.

**Comment by PhineasFreak** [comment]
Ven did not have ISRU replacements prior to the 1.9.1 release but i also may be wrong. I was basing my findings to the fact that this "small ISRU" doesn't have the correct model size as a drop - in replacement for either the stock small or the large ISRU.
