### ISSUE TITLE
Docking port ring diameter

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#76]
The newly revamped docking ports no longer match, in ring diameter, the unrevamped ones or the old-revamped ones (i.e. inline clampotron, let alone the Mk2 and Mk3 inline ones). This is a problem. :D The radial ones are no biggie because they can be arbitrarily scaled, but the inline ones can't be without changing the stack size. For that reason I would ask that the inner diameter of the ring on them match stock's inner diameter.

**Comment by VenVen** [comment]
Yeah, I only noticed that after I got to do the inline port and by then I didn't feel like stretching/ shrinking the rings to their proper scale. But If I may, why does the inner diameter of the port matter? (I'm assuming you're measuring the inner diameter from the inner edge of the extendable docking ring). Is this to stop cross-mod silliness?

**Comment by NathanKell** [comment]
Yep, pretty much. Though for us (RO) in particular, it's because we sized the parts based on the old inner diameters to match the inner diameters of known docking rings. We can of course rescale the new radial ports to preserve inner diameters, but we can't so easily do that to a stack part because that would rescale the fuselage around it too. That's especially true because you've not redone all the stock inline docking parts yet anyway, so there would have to be your diameter vs other diameter interaction.

**Comment by VenVen** [comment]
I've finished refitting the docking ports, and hopefully they'll be ready to go tomorrow.

**Comment by NathanKell** [comment]
<3 you're awesome as usual :)
