### ISSUE TITLE
Missing models

### ISSUE THREAD

**Issue by blowfishpro** [VenVen/Stock-Revamp#78]
When loading KSP with the latest commit (49d9550fca0b0b6924ffab701141bdff48467e61), I get the following errors:
```
PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Command/CommandPods/1-2' as model does not exist
PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/LVT15' as model does not exist
PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/ISRU/SmallISRU' as model does not exist
PartCompiler: Cannot clone model 'VenStockRevamp/Part Bin/NewParts/SoftTanks/LVN-2' as model does not exist
PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/IVA/Props/MECO' as model does not exist
```

**Comment by VenVen** [comment]
Ugh, it never ends... I'll have to look at these tomorrow, and hopefully fix them. Thanks for posting this!

**Comment by VenVen** [comment]
Alright, I believe all of these problems are now fixed. As it turned out several models were referenced poorly in their cfg's, one had a bad animation, and the other had a bad tag.
