### ISSUE TITLE
Upgrading to 1.0.5

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#80]
I notice that the engine patches still think ModuleAnimateHeat exists, and are still creating those modules. In 1.0.5, we switched to using FXAnimateThrottle. Check out how the stock engine configs have changed; your patches to them need to be updated. :)
(note that the mu files did not change, it's purely cfg changes, so you can replicate them)

**Comment by VenVen** [comment]
It seems that I've been working off of one of the old config template. I think that I've corrected the issue in the latest update.
