### ISSUE TITLE
Radial LFO Tanks wrong oxidizer ratio

### ISSUE THREAD

**Issue by adosikas** [VenVen/Stock-Revamp#81]
Seems to miss two @'s here, adding them fixes the ratio:
https://github.com/VenVen/Stock-Revamp/blob/master/GameData/VenStockRevamp/Part%20Bin/ExtraTanks.cfg#L161

(Shows 22 oxidizer ingame without)

**Comment by VenVen** [comment]
I think that I've fixed the problem, I've added the '@'s and changed the old values accordingly for the use with * or / wildcards.
