### ISSUE TITLE
Temporary 1.1 release

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#82]
@VenVen would you mind if I released a temporary 1.1 release based off the community's work, just to tide things over until you have time to properly port over?

**Comment by VenVen** [comment]
That's fine, it'll take me a few days to get most things working anyways. Between losing my more recent Unity scene file, and trying to get the new Unity animation system to work... It's been a bumpy road to say the least.

**Comment by NathanKell** [comment]
Oh no!

Let me know if I can help any on the conversion. I don't know a great deal about legs, but can probably help with other stuff. @sarbian and NecroBones will know best there I think.

Did you get my poke about how to fix the gimbals? They should be fairly easy to do.

**Comment by VenVen** [comment]
Yeah, It seems like the gimbal orientation matters now, I've tested some changes with some new engines and everything seems in order.

**Comment by NathanKell** [comment]
Cool!

Do you want me to push the community changes to the repo as a starting point?

**Comment by VenVen** [comment]
Sure
