### ISSUE TITLE
Releasing the 1.1 fixes?

### ISSUE THREAD

**Issue by NathanKell** [VenVen/Stock-Revamp#85]
@VenVen tracking down an error shows when doing the community fixes we missed removing the Asteroid Day clones so there are duplicate asteroid day parts. You however fixed that when you committed.
I'd like to release a revised version with that fixed (it causes issues in career, for example), but you've also committed a bunch of other changes/fixes/etc as well, and I'm not sure whether you'd rather:
- Have me do a release off the current state of the repo.
- Have me do a release prior to your commits (i.e. as of the community fixes commit, but with the above fixed too).
- Release yourself in your own good time.

Let me know! :)

**Comment by VenVen** [comment]
I'll release the current repo, assuming that that's alright and I'm not misreading what your saying. 

Hopefully I'll get the landing gear fixed sometime this week, And If I'm really lucky, the new wheels too.

**Comment by NathanKell** [comment]
Awesome! Let me know if there's anything I can help with, either on the releasing front or the wheels front. :)

**Comment by NathanKell** [comment]
Also I'll pop my current install over to the current state of the repo, just in case I notice anything funky.

**Comment by Tenvelden** [comment]
People are not having success with 1.9.3, maybe we should revert to 1.9.2?

 I wish I could figure out what was wrong but I'm no developer.
