### ISSUE TITLE
OX-2L 1x3 & OX-6L 1x3 panels missing deploy animations

### ISSUE THREAD

**Issue by Poodmund** [VenVen/Stock-Revamp#86]
It would seem that in the 1.9.3 release the following solar panels have had their ModuleDeployableSolarPanel animations set up incorrectly as they appear in the VAB as fully extended when the part is selected and do not have a right-click context menu to deploy the panel.

OX-2L 1x3 - VenStockRevamp/Squad/Parts/Electrical/SolarPanels/1x3S
OX-6L 1x3 - VenStockRevamp/Squad/Parts/Electrical/SolarPanels/1x3W

This renders the two panels... "hard to use" in their current state which is a shame especially with the OX-2L 1x3 panel as it is an early career acquisition. It seems a handful of mod users are rolling back to 1.9.2 due to this issue.

Comparing the configs to the previous version, the only change seems to be the model path which is specified correctly.

Is this a Unity environment animation issue?

**Comment by thomas15v** [comment]
I also had this issue. I figured out that the file `VenStockRevamp/Part Bin/ExtraElectrical.cfg` is corrupted in the zip file (at least on linux it is).

I just downloaded the file from [here](https://raw.githubusercontent.com/VenVen/Stock-Revamp/master/GameData/VenStockRevamp/Part%20Bin/ExtraElectrical.cfg) and replaced it. And it suddenly was working.

**Comment by Poodmund** [comment]
This issue seems to be resolved.
