### ISSUE TITLE
HeatShield 0.625m disappeared

### ISSUE THREAD

**Issue by Y3mo** [VenVen/Stock-Revamp#89]
The HeatShield0, which is added by VenStockRevamp, does no longer show up in game (eg tech tree).

**Comment by Kerbas-ad-astra** [comment]
The root cause of this seems to be a problem with HeatShieldS0.mu (see issue #83).

**Comment by Y3mo** [comment]
Whoops, somehow missed that.

**Comment by Kerbas-ad-astra** [comment]
Commit 8d8c98d brings the part back.
