### ISSUE TITLE
Attachment nodes LV-T45 and LV-900

### ISSUE THREAD

**Issue by Y3mo** [VenVen/Stock-Revamp#90]
The attachment nodes of LV-T45 and LV-900 are off, leading to part clipping.

Also the shrouds on the LV-T45 is too short.

Thank you for all your hard work, VSR really makes the game so much better!

**Comment by sick13** [comment]
just left the comment on ksp forums about this issue. (stupid me not looking here first)
also other engines have their node also off including the big white booster
