### ISSUE TITLE
Loading stuck at MK1 cargo bay

### ISSUE THREAD

**Issue by johante** [VenVen/Stock-Revamp#99]
When starting KSP with RSS and Realism Overhaul the game won't load. Issue happened after updating the mod through CKAN from 1.9.5 to 1.9.6.

Attached my log file if that helps, seems like it cant sort out loading MK1 Cargo Bay. Looks like issues start here: [LOG 15:35:30.930]

[KSP log.txt](https://github.com/VenVen/Stock-Revamp/files/752346/KSP.log.txt)

**Comment by Kerbas-ad-astra** [comment]
Are you still on KSP 1.1.3? VSR 1.9.6 is for KSP 1.2.2, older versions of KSP will choke on the new Payload category.

**Comment by johante** [comment]
I am on 1.1.3, but since CKAN said max ksp version was 1.1.3 I assumed it was safe to update. Is it possible to roll back to 1.9.5 in a non- destructive way maybe?

**Comment by Kerbas-ad-astra** [comment]
That's a question for the CKAN folks.

**Comment by johante** [comment]
Okay, thanks, I'll look into it
